language: go
go:
- 1.12.x
services:
- docker
addons:
  ssh_known_hosts: 52.55.252.242
sudo: true
jobs:
  include:
  - stage: build
    script:
    - go build
  - stage: push
    script:
    - bash docker_push.sh
  - stage: deploy
    before_script:
    - openssl aes-256-cbc -K $encrypted_70298db3af95_key -iv $encrypted_70298db3af95_iv -in blabla.pem.enc -out blabla.pem -d
    - chmod 400 blabla.pem
    script:
    - bash deploy.sh
      

stages:
  - build
  - name: push
    if: tag ~= /^deploy(\d)+$/
  - name: deploy
    if: tag ~= /^deploy(\d)+$/