version: '3.7'

services:
  service:
    restart: on-failure
    image: 777777missu7777777/gaming-website:${TAG}
    ports:
      - 8080:8080
    links:
      - db
    depends_on: 
      - db
    environment: 
      CONNECTION_STRING: 'root:root1234@tcp(db:3306)/GAMING_WEBSITE'
  
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    environment: 
      MYSQL_HOST: '%'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root1234'