CREATE DATABASE GAMING_WEBSITE;

USE GAMING_WEBSITE;

CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME NVARCHAR(50) NOT NULL,
    BALANCE BIGINT NOT NULL,
    PRIMARY KEY(USER_ID),
    CHECK(USERNAME <> ""),
    CHECK(BALANCE >= 0)
);

CREATE TABLE TOURNAMENTS (
    TOURNAMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    TOURNAMENT_NAME NAVARCHAR(50) NOT NULL,
    DEPOSIT BIGINT NOT NULL,
    PRIZE BIGINT NOT NULL,
    FINISHED BOOLEAN NOT NULL DEFAULT FALSE,
    CANCELED BOOLEAN NOT NULL DEFAULT_FALSE,
    PRIMARY_KEY(TOURNAMENT_ID),
    CHECK(TOURNAMENT_NAME <> ""),
    CHECK(DEPOSIT > 0),
    CHECK(PRIZE >= 0)
);

CREATE TABLE MTM_USER_TOURNAMENT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TOURNAMENT_ID BIGINT NOT NULL
);